/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTaskCreateRouteImport } from './routes/dashboard/task/create'
import { Route as DashboardProjectEditRouteImport } from './routes/dashboard/project/edit'
import { Route as DashboardProjectCreateRouteImport } from './routes/dashboard/project/create'
import { Route as DashboardProfileEditRouteImport } from './routes/dashboard/profile/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTaskCreateRoute = DashboardTaskCreateRouteImport.update({
  id: '/dashboard/task/create',
  path: '/dashboard/task/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectEditRoute = DashboardProjectEditRouteImport.update({
  id: '/dashboard/project/edit',
  path: '/dashboard/project/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectCreateRoute = DashboardProjectCreateRouteImport.update({
  id: '/dashboard/project/create',
  path: '/dashboard/project/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileEditRoute = DashboardProfileEditRouteImport.update({
  id: '/dashboard/profile/edit',
  path: '/dashboard/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/profile/edit': typeof DashboardProfileEditRoute
  '/dashboard/project/create': typeof DashboardProjectCreateRoute
  '/dashboard/project/edit': typeof DashboardProjectEditRoute
  '/dashboard/task/create': typeof DashboardTaskCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/profile/edit': typeof DashboardProfileEditRoute
  '/dashboard/project/create': typeof DashboardProjectCreateRoute
  '/dashboard/project/edit': typeof DashboardProjectEditRoute
  '/dashboard/task/create': typeof DashboardTaskCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/profile/edit': typeof DashboardProfileEditRoute
  '/dashboard/project/create': typeof DashboardProjectCreateRoute
  '/dashboard/project/edit': typeof DashboardProjectEditRoute
  '/dashboard/task/create': typeof DashboardTaskCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard/'
    | '/dashboard/profile/edit'
    | '/dashboard/project/create'
    | '/dashboard/project/edit'
    | '/dashboard/task/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/profile/edit'
    | '/dashboard/project/create'
    | '/dashboard/project/edit'
    | '/dashboard/task/create'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/dashboard/'
    | '/dashboard/profile/edit'
    | '/dashboard/project/create'
    | '/dashboard/project/edit'
    | '/dashboard/task/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProfileEditRoute: typeof DashboardProfileEditRoute
  DashboardProjectCreateRoute: typeof DashboardProjectCreateRoute
  DashboardProjectEditRoute: typeof DashboardProjectEditRoute
  DashboardTaskCreateRoute: typeof DashboardTaskCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/task/create': {
      id: '/dashboard/task/create'
      path: '/dashboard/task/create'
      fullPath: '/dashboard/task/create'
      preLoaderRoute: typeof DashboardTaskCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/project/edit': {
      id: '/dashboard/project/edit'
      path: '/dashboard/project/edit'
      fullPath: '/dashboard/project/edit'
      preLoaderRoute: typeof DashboardProjectEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/project/create': {
      id: '/dashboard/project/create'
      path: '/dashboard/project/create'
      fullPath: '/dashboard/project/create'
      preLoaderRoute: typeof DashboardProjectCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile/edit': {
      id: '/dashboard/profile/edit'
      path: '/dashboard/profile/edit'
      fullPath: '/dashboard/profile/edit'
      preLoaderRoute: typeof DashboardProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProfileEditRoute: DashboardProfileEditRoute,
  DashboardProjectCreateRoute: DashboardProjectCreateRoute,
  DashboardProjectEditRoute: DashboardProjectEditRoute,
  DashboardTaskCreateRoute: DashboardTaskCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
