/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTaskCreateNewRouteImport } from './routes/dashboard/task/create-new'
import { Route as DashboardTaskCreateRouteImport } from './routes/dashboard/task/create'
import { Route as DashboardProjectEditRouteImport } from './routes/dashboard/project/edit'
import { Route as DashboardProjectCreateRouteImport } from './routes/dashboard/project/create'
import { Route as DashboardProjectProjectIdRouteImport } from './routes/dashboard/project/$projectId'
import { Route as DashboardProfileEditRouteImport } from './routes/dashboard/profile/edit'
import { Route as DashboardProfileDisplayRouteImport } from './routes/dashboard/profile/display'
import { Route as DashboardInvitationsPendingRouteImport } from './routes/dashboard/invitations/pending'
import { Route as DashboardTaskTaskIdEditRouteImport } from './routes/dashboard/task/$taskId.edit'
import { Route as DashboardProjectProjectIdEditRouteImport } from './routes/dashboard/project/$projectId.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTaskCreateNewRoute = DashboardTaskCreateNewRouteImport.update({
  id: '/dashboard/task/create-new',
  path: '/dashboard/task/create-new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTaskCreateRoute = DashboardTaskCreateRouteImport.update({
  id: '/dashboard/task/create',
  path: '/dashboard/task/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectEditRoute = DashboardProjectEditRouteImport.update({
  id: '/dashboard/project/edit',
  path: '/dashboard/project/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectCreateRoute = DashboardProjectCreateRouteImport.update({
  id: '/dashboard/project/create',
  path: '/dashboard/project/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectProjectIdRoute =
  DashboardProjectProjectIdRouteImport.update({
    id: '/dashboard/project/$projectId',
    path: '/dashboard/project/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardProfileEditRoute = DashboardProfileEditRouteImport.update({
  id: '/dashboard/profile/edit',
  path: '/dashboard/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileDisplayRoute = DashboardProfileDisplayRouteImport.update({
  id: '/dashboard/profile/display',
  path: '/dashboard/profile/display',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInvitationsPendingRoute =
  DashboardInvitationsPendingRouteImport.update({
    id: '/dashboard/invitations/pending',
    path: '/dashboard/invitations/pending',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardTaskTaskIdEditRoute = DashboardTaskTaskIdEditRouteImport.update({
  id: '/dashboard/task/$taskId/edit',
  path: '/dashboard/task/$taskId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectProjectIdEditRoute =
  DashboardProjectProjectIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardProjectProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/invitations/pending': typeof DashboardInvitationsPendingRoute
  '/dashboard/profile/display': typeof DashboardProfileDisplayRoute
  '/dashboard/profile/edit': typeof DashboardProfileEditRoute
  '/dashboard/project/$projectId': typeof DashboardProjectProjectIdRouteWithChildren
  '/dashboard/project/create': typeof DashboardProjectCreateRoute
  '/dashboard/project/edit': typeof DashboardProjectEditRoute
  '/dashboard/task/create': typeof DashboardTaskCreateRoute
  '/dashboard/task/create-new': typeof DashboardTaskCreateNewRoute
  '/dashboard/project/$projectId/edit': typeof DashboardProjectProjectIdEditRoute
  '/dashboard/task/$taskId/edit': typeof DashboardTaskTaskIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/invitations/pending': typeof DashboardInvitationsPendingRoute
  '/dashboard/profile/display': typeof DashboardProfileDisplayRoute
  '/dashboard/profile/edit': typeof DashboardProfileEditRoute
  '/dashboard/project/$projectId': typeof DashboardProjectProjectIdRouteWithChildren
  '/dashboard/project/create': typeof DashboardProjectCreateRoute
  '/dashboard/project/edit': typeof DashboardProjectEditRoute
  '/dashboard/task/create': typeof DashboardTaskCreateRoute
  '/dashboard/task/create-new': typeof DashboardTaskCreateNewRoute
  '/dashboard/project/$projectId/edit': typeof DashboardProjectProjectIdEditRoute
  '/dashboard/task/$taskId/edit': typeof DashboardTaskTaskIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/invitations/pending': typeof DashboardInvitationsPendingRoute
  '/dashboard/profile/display': typeof DashboardProfileDisplayRoute
  '/dashboard/profile/edit': typeof DashboardProfileEditRoute
  '/dashboard/project/$projectId': typeof DashboardProjectProjectIdRouteWithChildren
  '/dashboard/project/create': typeof DashboardProjectCreateRoute
  '/dashboard/project/edit': typeof DashboardProjectEditRoute
  '/dashboard/task/create': typeof DashboardTaskCreateRoute
  '/dashboard/task/create-new': typeof DashboardTaskCreateNewRoute
  '/dashboard/project/$projectId/edit': typeof DashboardProjectProjectIdEditRoute
  '/dashboard/task/$taskId/edit': typeof DashboardTaskTaskIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-callback'
    | '/login'
    | '/signup'
    | '/dashboard/'
    | '/dashboard/invitations/pending'
    | '/dashboard/profile/display'
    | '/dashboard/profile/edit'
    | '/dashboard/project/$projectId'
    | '/dashboard/project/create'
    | '/dashboard/project/edit'
    | '/dashboard/task/create'
    | '/dashboard/task/create-new'
    | '/dashboard/project/$projectId/edit'
    | '/dashboard/task/$taskId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-callback'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/dashboard/invitations/pending'
    | '/dashboard/profile/display'
    | '/dashboard/profile/edit'
    | '/dashboard/project/$projectId'
    | '/dashboard/project/create'
    | '/dashboard/project/edit'
    | '/dashboard/task/create'
    | '/dashboard/task/create-new'
    | '/dashboard/project/$projectId/edit'
    | '/dashboard/task/$taskId/edit'
  id:
    | '__root__'
    | '/'
    | '/auth-callback'
    | '/login'
    | '/signup'
    | '/dashboard/'
    | '/dashboard/invitations/pending'
    | '/dashboard/profile/display'
    | '/dashboard/profile/edit'
    | '/dashboard/project/$projectId'
    | '/dashboard/project/create'
    | '/dashboard/project/edit'
    | '/dashboard/task/create'
    | '/dashboard/task/create-new'
    | '/dashboard/project/$projectId/edit'
    | '/dashboard/task/$taskId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardInvitationsPendingRoute: typeof DashboardInvitationsPendingRoute
  DashboardProfileDisplayRoute: typeof DashboardProfileDisplayRoute
  DashboardProfileEditRoute: typeof DashboardProfileEditRoute
  DashboardProjectProjectIdRoute: typeof DashboardProjectProjectIdRouteWithChildren
  DashboardProjectCreateRoute: typeof DashboardProjectCreateRoute
  DashboardProjectEditRoute: typeof DashboardProjectEditRoute
  DashboardTaskCreateRoute: typeof DashboardTaskCreateRoute
  DashboardTaskCreateNewRoute: typeof DashboardTaskCreateNewRoute
  DashboardTaskTaskIdEditRoute: typeof DashboardTaskTaskIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/task/create-new': {
      id: '/dashboard/task/create-new'
      path: '/dashboard/task/create-new'
      fullPath: '/dashboard/task/create-new'
      preLoaderRoute: typeof DashboardTaskCreateNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/task/create': {
      id: '/dashboard/task/create'
      path: '/dashboard/task/create'
      fullPath: '/dashboard/task/create'
      preLoaderRoute: typeof DashboardTaskCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/project/edit': {
      id: '/dashboard/project/edit'
      path: '/dashboard/project/edit'
      fullPath: '/dashboard/project/edit'
      preLoaderRoute: typeof DashboardProjectEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/project/create': {
      id: '/dashboard/project/create'
      path: '/dashboard/project/create'
      fullPath: '/dashboard/project/create'
      preLoaderRoute: typeof DashboardProjectCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/project/$projectId': {
      id: '/dashboard/project/$projectId'
      path: '/dashboard/project/$projectId'
      fullPath: '/dashboard/project/$projectId'
      preLoaderRoute: typeof DashboardProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile/edit': {
      id: '/dashboard/profile/edit'
      path: '/dashboard/profile/edit'
      fullPath: '/dashboard/profile/edit'
      preLoaderRoute: typeof DashboardProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile/display': {
      id: '/dashboard/profile/display'
      path: '/dashboard/profile/display'
      fullPath: '/dashboard/profile/display'
      preLoaderRoute: typeof DashboardProfileDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/invitations/pending': {
      id: '/dashboard/invitations/pending'
      path: '/dashboard/invitations/pending'
      fullPath: '/dashboard/invitations/pending'
      preLoaderRoute: typeof DashboardInvitationsPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/task/$taskId/edit': {
      id: '/dashboard/task/$taskId/edit'
      path: '/dashboard/task/$taskId/edit'
      fullPath: '/dashboard/task/$taskId/edit'
      preLoaderRoute: typeof DashboardTaskTaskIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/project/$projectId/edit': {
      id: '/dashboard/project/$projectId/edit'
      path: '/edit'
      fullPath: '/dashboard/project/$projectId/edit'
      preLoaderRoute: typeof DashboardProjectProjectIdEditRouteImport
      parentRoute: typeof DashboardProjectProjectIdRoute
    }
  }
}

interface DashboardProjectProjectIdRouteChildren {
  DashboardProjectProjectIdEditRoute: typeof DashboardProjectProjectIdEditRoute
}

const DashboardProjectProjectIdRouteChildren: DashboardProjectProjectIdRouteChildren =
  {
    DashboardProjectProjectIdEditRoute: DashboardProjectProjectIdEditRoute,
  }

const DashboardProjectProjectIdRouteWithChildren =
  DashboardProjectProjectIdRoute._addFileChildren(
    DashboardProjectProjectIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardInvitationsPendingRoute: DashboardInvitationsPendingRoute,
  DashboardProfileDisplayRoute: DashboardProfileDisplayRoute,
  DashboardProfileEditRoute: DashboardProfileEditRoute,
  DashboardProjectProjectIdRoute: DashboardProjectProjectIdRouteWithChildren,
  DashboardProjectCreateRoute: DashboardProjectCreateRoute,
  DashboardProjectEditRoute: DashboardProjectEditRoute,
  DashboardTaskCreateRoute: DashboardTaskCreateRoute,
  DashboardTaskCreateNewRoute: DashboardTaskCreateNewRoute,
  DashboardTaskTaskIdEditRoute: DashboardTaskTaskIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
